on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: 'changelogs'
          changeLogFile: 'changelog-main.yaml'
          username: ${{ secrets.LIQUIBASE_ODS_USERNAME }}
          password: ${{ secrets.LIQUIBASE_ODS_PASSWORD }}
          url: ${{ secrets.LIQUIBASE_ODS_JDBC_URL }}
          proLicenseKey: ${{ secrets.LIQUIBASE_PRO_KEY }}
